name: MLOps- Fundamentals with Fast API


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test_requirements.txt

      - name: Train pipeline
        run: |
          python bikeshare_model/train_pipeline.py

      - name: Test with pytest
        run: |
          pytest
          
      - name: Create *.whl file
        run: |
          python -m build


      #Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
